DEBUG = False

MARGIN = 20
PRELIMINARY_CONNECTION_TRACKS_WIDTH = 123
CONNECTION_TRACKS_MARGIN = 20
INTER_SOCKET_MARGIN = 60
INTER_TRACK_MARGIN = 15
BASE_PATH = "assets"
OUTPUT_PATH = "output"
GAUGE_WIDTHS: dict[int, int] = {
    12: 15,
    22: 2
}