DEBUG = False

MARGIN = 20
PRE_CONNECTION_MARGIN = 20
CONNECTION_TRACKS_WIDTH = 100
INTER_SOCKET_MARGIN = 60
INTER_TRACK_MARGIN = 15
BASE_PATH = "assets"
OUTPUT_PATH = "output"
GAUGE_WIDTHS: dict[int, int] = {
    12: 15,
    22: 2
}